CREATE CACHED TABLE AccountTypes
	(
	 ActTypeID   INT GENERATED BY DEFAULT AS IDENTITY (START WITH 0),
	 ActTypeName VARCHAR(50)
    );

  CREATE CACHED TABLE Accounts
	(
	  ActID 	 INT GENERATED BY DEFAULT AS IDENTITY (START WITH 0),
	  ActTypeID  INT,
	  ActName 	 VARCHAR(100),
	  ActNumber  VARCHAR(50),
	  ActBalance DECIMAL(15,4)
	);

  CREATE CACHED TABLE Transactions
	(
	  TranID 		   BIGINT GENERATED BY DEFAULT AS  IDENTITY (START WITH 0),
	  ActID 		   INT,
	  TranDate	       DATETIME,
	  TranMemo         VARCHAR(255),
	  TranAmount  DECIMAL(15,4)
	);
  
  CREATE CACHED TABLE MonthlyBalance
	(
	  ActID 	 INT,
	  Yr		 INT,
	  Mth		 INT,
	  ActBalance DECIMAL(15,4)
	);
  
  CREATE CACHED TABLE Budget
	(
	  BudgetID 	   INT GENERATED BY DEFAULT AS IDENTITY (START WITH 0),
	  BudgetName   VARCHAR(100)
	);
 
  CREATE CACHED TABLE BudgetDetail
	(
	  BudgetID 	   INT,
	  ActID        INT,
	  Mth          INT,
	  Amount       DECIMAL(15,4)
	); 
  
  CREATE CACHED TABLE AppSettings
	(
	  AppVersion   VARCHAR(15)
	); 

  CREATE CACHED TABLE AccountTemplates
  (
  	ActTypeID    INT,
	ActName 	 VARCHAR(100)
  );
  
  CREATE CACHED TABLE ImportHistory
  (
  	ActID		INT,
  	Memo		VARCHAR(100)
  );

  CREATE CACHED TABLE RecurHeader
	(
	  RecurID 	   INT GENERATED BY DEFAULT AS IDENTITY (START WITH 0),
	  Memo   VARCHAR(255),
	  ActID		INT,
	  OffsetID		INT,
	  NextRunDate	       DATETIME,
	  Amount       DECIMAL(15,4),
	  FrequencyID INT
	);
	
	CREATE CACHED TABLE RecurDetail
	(
	  RecurTranID 	   INT GENERATED BY DEFAULT AS IDENTITY (START WITH 0),
	  RecurID 	   INT,
	  TranDate	       DATETIME
	);
  
  ALTER TABLE  RecurHeader ADD
    CONSTRAINT RecurHeader_RecurID
    UNIQUE (RecurID);

  ALTER TABLE  RecurDetail ADD
    CONSTRAINT RecurDetail_RecurTranID
    UNIQUE (RecurTranID);
 
  ALTER TABLE RecurDetail ADD 
	CONSTRAINT FK_RecurDetail_RecurHeader 
	 FOREIGN KEY (RecurID) REFERENCES RecurHeader (RecurID);
    
  ALTER TABLE AccountTypes ADD
   CONSTRAINT AccountTypes_ActTypeName
	UNIQUE(ActTypeName);

  ALTER TABLE Accounts ADD
   CONSTRAINT Accounts_ActName
	UNIQUE(ActName);

  ALTER TABLE AccountTemplates ADD
  	CONSTRAINT AccountTemplates_ActName
  	 UNIQUE(ActTypeID, ActName);
  	 
   ALTER TABLE ImportHistory ADD
  	CONSTRAINT ImportHistory_ActID
  	 UNIQUE(ActID, Memo);

  ALTER TABLE Transactions ADD 
	CONSTRAINT FK_Transactions_Accounts 
	 FOREIGN KEY (ActID) REFERENCES Accounts (ActID);

 ALTER TABLE Accounts ADD 
	CONSTRAINT FK_Accounts_AccountTypes
	 FOREIGN KEY (ActTypeID) REFERENCES AccountTypes (ActTypeID);

 ALTER TABLE MonthlyBalance ADD
   CONSTRAINT MonthlyBalance_1
	UNIQUE(ActId, Yr, Mth);

ALTER TABLE Budget ADD
   CONSTRAINT Budget_BudgetName
	UNIQUE(BudgetName);
	
ALTER TABLE BudgetDetail ADD
   CONSTRAINT BudgetDetail_BudgetIdMonth
	UNIQUE(BudgetID, ActID, Mth);

ALTER TABLE BudgetDetail ADD 
	CONSTRAINT FK_BudgetDetail_Budget
	 FOREIGN KEY (BudgetID) REFERENCES Budget (BudgetID);

ALTER TABLE BudgetDetail ADD 
	CONSTRAINT FK_BudgetDetail_ActID
	 FOREIGN KEY (ActID) REFERENCES Accounts (ActID);
	 
ALTER TABLE MonthlyBalance ADD 
	CONSTRAINT FK_MonthlyBalance_Accounts
	 FOREIGN KEY (ActID) REFERENCES Accounts (ActID);


  INSERT INTO AppSettings (AppVersion) VALUES ('0.3.0');
  INSERT INTO AccountTypes (ActTypeName) VALUES('Bank');
  INSERT INTO AccountTypes (ActTypeName) VALUES('Expense');
  INSERT INTO AccountTypes (ActTypeName) VALUES('Income');
  INSERT INTO AccountTypes (ActTypeName) VALUES ('Liability');
  
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Electric' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Telephone' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Groceries' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Eat Out' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Bank Fees' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Auto Insurance' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Auto Repairs' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Hobbies' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Clothing' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'HBA' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Donations' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Property Taxes' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Income Taxes' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Recreation' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Home Improvement' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Medical' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Childcare' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'ATM Withdrawal' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Fuel' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Grooming' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Cable/Internet' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Sanitation' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Water Utility' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Expense';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Income' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Income';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Income Spouse' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Income';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Income Interest' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Income';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Primary Checking' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Bank';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Primary Savings' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Bank';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Credit Card' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Liability';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'First Mortgage' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Liability';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Second Mortgage' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Liability';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Car Loan' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Liability';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Home Equity Loan' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Liability';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Personal Loan' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Liability';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'Line Of Credit' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Liability';
  INSERT INTO AccountTemplates(ActName, ActTypeID) SELECT 'School Loan' AS ActName, AccountTYpes.ACTTYPEID FROM AccountTypes WHERE ACTTYPENAME = 'Liability';
  
  commit;
  